package config

import (
	"fmt"
	"testing"
)

// tests if appNameToIP works as intended
func TestAppNameToIP(t *testing.T) {
	name := "test-app"
	target := "172.16.7.24" // pre-calculated IP for "test-app"
	actual := appNameToIP(name)

	if actual != target {
		t.Error(fmt.Sprintf("Expected IP '%s' got '%s'", target, actual))
	}
}

// tests to ensure that IPs generated by appNameToIP are unique for similar names
func TestAppNameToIPUnique(t *testing.T) {
	var name string

	name = "test-app"
	first := appNameToIP(name)

	name = "app-test"
	second := appNameToIP(name)

	if first == second {
		t.Error("IPs arent unique")
	}
}
