// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/nanobox-io/nanobox-cli/config (interfaces: Config)

package mock_config

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Config interface
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *_MockConfigRecorder
}

// Recorder for MockConfig (not exported)
type _MockConfigRecorder struct {
	mock *MockConfig
}

func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &_MockConfigRecorder{mock}
	return mock
}

func (_m *MockConfig) EXPECT() *_MockConfigRecorder {
	return _m.recorder
}

func (_m *MockConfig) Fatal(_param0 string, _param1 string) {
	_m.ctrl.Call(_m, "Fatal", _param0, _param1)
}

func (_mr *_MockConfigRecorder) Fatal(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Fatal", arg0, arg1)
}

func (_m *MockConfig) Root() string {
	ret := _m.ctrl.Call(_m, "Root")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockConfigRecorder) Root() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Root")
}
