// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/nanobox-io/nanobox/util/file/hosts (interfaces: Host)

package mock_hosts

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Host interface
type MockHost struct {
	ctrl     *gomock.Controller
	recorder *_MockHostRecorder
}

// Recorder for MockHost (not exported)
type _MockHostRecorder struct {
	mock *MockHost
}

func NewMockHost(ctrl *gomock.Controller) *MockHost {
	mock := &MockHost{ctrl: ctrl}
	mock.recorder = &_MockHostRecorder{mock}
	return mock
}

func (_m *MockHost) EXPECT() *_MockHostRecorder {
	return _m.recorder
}
